import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import Script from 'next/script';
import App from './_app';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         {children}
         <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
        </body>
    </html>
  )
}
